import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { dark } from "@clerk/themes";
import "./globals.css";
import Navbar from "./components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NextMart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="">
      <ClerkProvider
        appearance={{
          theme: dark,
        }}
      >
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <Navbar />
            <main className="mx-auto px-4 sm:px-8 container min-h-screen">
              {children}
            </main>
          </body>
        </html>
      </ClerkProvider>
    </div>
  );
}
